"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ───────────────────────────────────────────────
# 1. Define BASE_DIR first — everything depends on it
# ───────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent


# ───────────────────────────────────────────────
# 2. Load environment variables
#    Priority: DJANGO_ENV_FILE env var > .env.local > .env
# ───────────────────────────────────────────────
env_file = os.getenv("DJANGO_ENV_FILE", ".env.local")

# Try to load the chosen env file
env_path = BASE_DIR / env_file
if env_path.exists():
    load_dotenv(env_path)
else:
    # Fallback to plain .env if the specific one doesn't exist
    fallback = BASE_DIR / ".env"
    if fallback.exists():
        load_dotenv(fallback)
    else:
        print(f"Warning: No .env file found (tried {env_file} and .env)")


# ───────────────────────────────────────────────
# 3. Core security settings
# ───────────────────────────────────────────────

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is missing! Check your .env file.")

DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes", "on")

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,::1"
).split(",")


# ───────────────────────────────────────────────
# Application definition
# ───────────────────────────────────────────────

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'api',              # your main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ───────────────────────────────────────────────
# Database
# ───────────────────────────────────────────────

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# ───────────────────────────────────────────────
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# ───────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ───────────────────────────────────────────────
# Internationalization
# ───────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Karachi')   # good choice for Lahore

USE_I18N = True

USE_TZ = True


# ───────────────────────────────────────────────
# Static files (CSS, JavaScript, Images)
# ───────────────────────────────────────────────

STATIC_URL = 'static/'

# Optional – add when you deploy
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [BASE_DIR / 'static']


# ───────────────────────────────────────────────
# REST Framework configuration
# ───────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # Uncomment next line if you want browsable API in development
        # 'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}


# ───────────────────────────────────────────────
# Optional: Add these when going to production
# ───────────────────────────────────────────────

# SECURE_SSL_REDIRECT = not DEBUG
# SESSION_COOKIE_SECURE = not DEBUG
# CSRF_COOKIE_SECURE = not DEBUG
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True